-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 20:13:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema M14_Botiga_Quadros
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `M14_Botiga_Quadros` ;

-- -----------------------------------------------------
-- Schema M14_Botiga_Quadros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `M14_Botiga_Quadros` DEFAULT CHARACTER SET utf8 ;
USE `M14_Botiga_Quadros` ;

-- -----------------------------------------------------
-- Table `M14_Botiga_Quadros`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `M14_Botiga_Quadros`.`store` ;

CREATE TABLE IF NOT EXISTS `M14_Botiga_Quadros`.`store` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `maxCapacity` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `M14_Botiga_Quadros`.`frames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `M14_Botiga_Quadros`.`frames` ;

CREATE TABLE IF NOT EXISTS `M14_Botiga_Quadros`.`frames` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NULL DEFAULT NULL,
  `price` INT(11) NOT NULL,
  `storeEntryDate` DATETIME NOT NULL,
  `storeId` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `storeId`),
  INDEX `availableAt_idx` (`storeId` ASC),
  CONSTRAINT `availableAt`
    FOREIGN KEY (`storeId`)
    REFERENCES `M14_Botiga_Quadros`.`store` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
